name: Upload build artifacts
on:
  push:
    branches:
      - main
      - "**"
  pull_request:
  workflow_dispatch:
    inputs:
      commit:
        description: If the commit you want to test isn't the head of a branch, provide its SHA here
        required: false
jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm ci

      - run: npm run build:lib

      - run: npm pack

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: |
            ${{ github.workspace }}/*.tgz

  precompile-bindings:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-2019, ubuntu-latest]
        node-version: [12.x, 14.x, 16.x, 18.x]
        target: [x64]
        host: [x64]
    runs-on: ${{ matrix.os }}
    # Build artifacts are only needed for releasing workflow.
    # if: startsWith(github.ref, 'refs/heads/release/')
    name: ${{ matrix.os }} (node=${{ matrix.node-version }}, host=${{ matrix.host }}, target=${{ matrix.target }})
    steps:
      - name: Check out current commit
        uses: actions/checkout@v3
        with:
          ref: ${{ env.HEAD_COMMIT }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.host }}

      - name: Setup windows build tools
        uses: microsoft/setup-msbuild@v1.1
        if: ${{ runner.os == 'Windows' }}
        with:
          msbuild-architecture: ${{ matrix.target }}

      - name: Install dependencies
        run: npm install

      - name: Configure gyp
        run: npm run build:configure --arch=${{ matrix.target }}

      - name: Build bindings
        run: npm run build:bindings --arch=${{ matrix.target }}

      - name: Test
        run: npm run test
      
      - name: Copy Binary
        run: node scripts/copy-target.js

      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}.${{ matrix.node-version }}.${{ matrix.host }}.${{ github.sha }}
          path: |
            ${{ github.workspace }}/binaries/