name: "ci"
on:
  pull_request:
  push:
    branches:
      - main
      - "release/*"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install yarn
        run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: |
          git config clangFormat.binary node_modules/.bin/clang-format
          git config clangFormat.style file
          yarn lint

  build-test-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-2019, ubuntu-latest]
        node-version: [14.x, 16.x, 18.x, 20.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: npm install -g yarn
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: yarn clean

      - name: Setup windows build tools
        uses: microsoft/setup-msbuild@v1.1
        if: ${{ runner.os == 'Windows' }}

      - run: yarn install
      - run: yarn build:configure
      - run: yarn build
      - run: yarn test --silent
