name: 'abi-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'release/*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run lint
  compile:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-2019, ubuntu-latest]
        node-version: [20.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup windows build tools
        uses: microsoft/setup-msbuild@v1.1
        if: ${{ runner.os == 'Windows' }}

      - run: npm install
      - run: npm run build:configure
      - run: npm run build
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compile-test-binaries-${{ github.sha }}
          path: |
            ${{ github.workspace }}/lib/binaries/*.node
  test:
    needs: compile
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-2019, ubuntu-latest]
        node-version: [12.x, 14.x, 16.x, 18.x, 20.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup windows build tools
        uses: microsoft/setup-msbuild@v1.1
        if: ${{ runner.os == 'Windows' }}

      - run: npm install
      - run: rm -rf lib/binaries
      - uses: actions/download-artifact@v3
        with: 
          name: compile-test-binaries-${{ github.sha }}
          path: lib/binaries
      - run: npm run test

